### ISSUE TITLE
Performant/cleaner _monthlytable

### ISSUE THREAD

**Issue by bmpalatiello** [lobnek/pyutil#10]
Removing some of the lambdas in `_monthlytable` cleans things up a bit and improves performance: 

```
def _monthlytable(nav):
    """
    Get a table of monthly returns

    :param nav:

    :return:
    """
    r = np.log(1 + nav.pct_change(1).dropna())
    mo = np.exp(r.groupby([r.index.year, r.index.month]).sum()) - 1
    frame = mo.unstack(level=1).rename(columns=lambda x: calendar.month_abbr[x])
    ytd = (frame + 1.0).prod(axis=1) - 1.0
    frame["STDev"] = np.sqrt(12) * frame.std(axis=1)
    frame["YTD"] = ytd
    frame.index.name = "Year"
    frame.columns.name = None
    return frame.iloc[::-1]
```

Performance differences:
```
# Current version
108 ms ± 648 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

# This version
13.5 ms ± 230 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by tschm** [comment]
Ah, this slipped through. Will change. Many thanks. Having said that I love my lambdas ;-)

**Comment by tschm** [comment]
I have to test thist
import calendar
import numpy as np


def _cumulate(x):
    return (1 + x).prod() - 1.0

def monthlytable(nav):
    """
    Get a table of monthly returns

    :param nav:

    :return:
    """
    r = nav.pct_change().dropna()
    # Works better in the first month
    # Compute all the intramonth-returns, instead of reapplying some monthly resampling of the NAV
    return_monthly = r.groupby([r.index.year, r.index.month]).apply(_cumulate)
    frame = return_monthly.unstack(level=1).rename(columns=lambda x: calendar.month_abbr[x])
    ytd = frame.apply(_cumulate, axis=1)
    frame["STDev"] = np.sqrt(12) * frame.std(axis=1)
    # make sure that you don't include the column for the STDev in your computation
    frame["YTD"] = ytd
    frame.index.name = "Year"
    frame.columns.name = None
    # most recent years on top
    return frame.iloc[::-1]
