### ISSUE TITLE
Performant iron time

### ISSUE THREAD

**Issue by bmpalatiello** [lobnek/pyutil#8]
The current implementation of iron time is relatively slow. Depending on how intricate you get with the types of resampling for weekly and monthly resampling you can make the block:

```
moments = [self.index[0]]
resample = self.weights.resample(rule=rule).last()
for t in resample.index:
           moments.append([a for a in self.index if a <= t][-1])
```

assuming holidays are taken into account in the weights index:

```
idx = self.weights.index

monthly = sorted(list(set(pd.Series(data=idx).groupby([idx.year, idx.month]).nth(-1))))
weekly = sorted(list(set(pd.Series(data=idx).groupby(idx.map(lambda x: x.isocalendar()[0:2])).nth(-1))))
```

You're approach, as well as this one, returns the last date whether or not it is the last day in the period. For example, today is 1/17/19 which is not the last day of this week (1/18/19 is) so the last date it will return is 1/17/19.

**Comment by tschm** [comment]
@bmpalatiello i will have a look. I really appreciate your feedback. I may incorporate:
`
import pandas as pd

if __name__ == '__main__':
    idx = pd.DatetimeIndex(start=pd.Timestamp("2018-10-28"), periods=100, freq="D")
    print(idx)

    x = pd.Series(data=idx, index=idx)
    print(x)

    # monthly
    print(sorted(x.groupby([idx.year, idx.month]).last().values))

    # weekly
    print(sorted(x.groupby([idx.year, idx.week]).last().values))`
`

**Comment by bmpalatiello** [comment]
Yes, that is cleaner. I was going off the top of my head but didn't want to forget anything! 

Also, if you have a DatetimeIndex its faster to do `idx.to_series()` as opposed to creating a new Series with `pd.Series(data=idx, index=idx)`.

**Comment by bmpalatiello** [comment]
Also, you need to use the isocalendar in the weekly resample for the edge cases where the year ends in the middle of the week. 

For example, using your approach returns 12/31/2018 which is a Monday because it is the last day of the last week in the calendar year. Instead of returning 12/31/2018 it should return 1/4/2019.

**Comment by tschm** [comment]
good observation with the isocalendar

**Comment by tschm** [comment]
Hi Brett, if you have some time I would appreciate if we run through
https://guides.github.com/introduction/flow/
You then will have forever a trace in this project :-)

**Comment by bmpalatiello** [comment]
#9
